# This file was generated by GoReleaser. DO NOT EDIT.
class Diu < Formula
  desc "AI-powered command line assistant that analyzes terminal errors and provides solutions"
  homepage "https://github.com/techccy/diu-assistant"
  version "{{ .Version }}"

  if OS.mac? && Hardware::CPU.arm?
    url "{{ .URLs.darwin_arm64 }}"
    sha256 "{{ .Checksums.darwin_arm64 }}"
  elsif OS.mac? && Hardware::CPU.intel?
    url "{{ .URLs.darwin_amd64 }}"
    sha256 "{{ .Checksums.darwin_amd64 }}"
  elsif OS.linux? && Hardware::CPU.intel?
    url "{{ .URLs.linux_amd64 }}"
    sha256 "{{ .Checksums.linux_amd64 }}"
  elsif OS.linux? && Hardware::CPU.arm?
    url "{{ .URLs.linux_arm64 }}"
    sha256 "{{ .Checksums.linux_arm64 }}"
  end

  def install
    bin.install "diu-core"
  end

  test do
    system "#{bin}/diu-core", "--version"
  end

  def post_install
    ohai "Run 'diu-core --init' to initialize the shell integration"
  end
end
